# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [2]:
import numpy as np
import sys

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [3]:
python_array = [0] * 1000
print(f"Size of Python array: {sys.getsizeof(python_array)} bytes")

Size of Python array: 8056 bytes


In [4]:
numpy_array = np.zeros(1000, dtype=np.int8)
print(f"Size of Numpy array: {numpy_array.nbytes} bytes")

Size of Numpy array: 1000 bytes


## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [6]:
float_array = np.array([0.5, 2.3, 5.1, 7.8, 9.4, 3.2])
float_array[[0, 2, -1]]

array([0.5, 5.1, 3.2])

## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [18]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
array[1:6].sum()

np.float64(27.4)

## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [19]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [20]:
A.mean(axis=0)

array([2. , 8.4])

### Task 5.2 Get the standard deviation by `y` axis

In [26]:
np.std(A, axis=0)

array([0.89442719, 1.8547237 ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [27]:
np.sum(A, axis=0)

array([10, 42])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [28]:
A[:2]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [29]:
A[[0, 2, -1]]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [30]:
# Python code
[i for i in range(1000000)]

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [33]:
import time
np.arange(1000000)

start_time_python = time.time()
python_result = [i for i in range(1000000)]
end_time_python = time.time()

start_time_numpy = time.time()
numpy_result = np.arange(1000000)
end_time_numpy = time.time()

python_time = end_time_python - start_time_python
numpy_time = end_time_numpy - start_time_numpy

python_time, numpy_time

(0.040235280990600586, 0.002521991729736328)

### Task 6.2

In [35]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

%time unknown_signature(vector1, vector2)
result

CPU times: total: 0 ns
Wall time: 0 ns


0

In [38]:
def unknown_signature_numpy(vector1, vector2):
    return np.dot(vector1, vector2)

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
result = 0

%time unknown_signature_numpy(vector1, vector2)
result


CPU times: total: 0 ns
Wall time: 0 ns


0.0

### Task 6.3

In [42]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]
import time
start_time = time.time()
result_python = unknown_signature(matrix1, matrix2)
end_time = time.time()
print("Python Result:", result_python)
print("Execution Time (Python):", end_time - start_time)

Python Result: [[5, 12], [21, 32]]
Execution Time (Python): 0.0


In [41]:
def unknown_signature_numpy(matrix1, matrix2):
    return np.multiply(matrix1, matrix2)

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
start_time = time.time()
result_numpy = unknown_signature_numpy(matrix1, matrix2)
end_time = time.time()
print("NumPy Result:", result_numpy)
print("Execution Time (NumPy):", end_time - start_time)

NumPy Result: [[ 5 12]
 [21 32]]
Execution Time (NumPy): 0.0


### Task 6.4

In [ ]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]

In [45]:
def unknown_signature_numpy(lst):
    return np.mean(lst)

lst = [1, 2, 3, 4, 5]
unknown_signature_numpy(lst)
%time unknown_signature_numpy(lst)

CPU times: total: 0 ns
Wall time: 0 ns


np.float64(3.0)

## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [31]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

[0, 2, 0, 4, 0]

In [46]:
def unknown_signature_numpy(lst, mask, new_value):
    lst = np.array(lst)
    mask = np.array(mask)
    
    lst[mask] = new_value
    return lst

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature_numpy(lst, mask, new_value)

array([0, 2, 0, 4, 0])

### Task 7.2

In [48]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [47]:
def unknown_signature_numpy(lst1, lst2):
    arr1 = np.array(lst1)
    arr2 = np.array(lst2)
    
    bitwise_complement = np.bitwise_not(arr1)
    
    bitwise_and = np.bitwise_and(arr1, arr2)
    
    bitwise_or = np.bitwise_or(arr1, arr2)
    
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
unknown_signature_numpy(list1, list2)

(array([ -6,  -3,  -8,  -5, -10]),
 array([1, 2, 1, 0, 8]),
 array([ 7,  6,  7, 12, 11]))

### Task 7.3 Optional

In [34]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [49]:
def unknown_signature_numpy(lst):
    arr = np.array(lst)
    mask = (arr % 2 == 0) & ((arr % 3 == 0) | (arr > 10))
    modified_arr = (arr[mask] ^ 7) + 2
    return modified_arr

my_list = [6, 9, 12, 14, 17, 20]
unknown_signature_numpy(my_list)

array([ 3, 13, 11, 21])